// Métadonnées des 22 régions de Madagascar
// Couleurs choropleth + données de référence pour l'UI

export const REGION_COLORS = {
  'Alaotra-Mangoro':      '#63be7b',
  "Amoron'i Mania":       '#8dd3c7',
  'Analamanga':           '#377eb8',
  'Analanjirofo':         '#4daf4a',
  'Androy':               '#e41a1c',
  'Anosy':                '#fb9a99',
  'Atsimo-Andrefana':     '#fdbf6f',
  'Atsimo-Atsinanana':    '#ff7f00',
  'Atsinanana':           '#a65628',
  'Betsiboka':            '#cab2d6',
  'Boeny':                '#6a3d9a',
  'Bongolava':            '#b15928',
  'Diana':                '#1f78b4',
  'Ihorombe':             '#7f7f7f',
  'Itasy':                '#33a02c',
  'Matsiatra Ambony':     '#f4e429',
  'Melaky':               '#3289be',
  'Menabe':               '#bf5b17',
  'Sava':                 '#a6cee3',
  'Sofia':                '#33a02c',
  'Vakinankaratra':       '#fb9a99',
  'Vatovavy-Fitovinany':  '#9970ab',
};

export const REGION_INFO = {
  'Alaotra-Mangoro':     { capital: 'Ambatondrazaka',  area: 31948, population: 1255514 },
  "Amoron'i Mania":      { capital: 'Ambositra',       area: 16141, population: 833919 },
  'Analamanga':          { capital: 'Antananarivo',    area: 16911, population: 3618128 },
  'Analanjirofo':        { capital: 'Fenoarivo',       area: 21930, population: 1153917 },
  'Androy':              { capital: 'Ambovombe',       area: 19317, population: 903376 },
  'Anosy':               { capital: 'Taolagnaro',      area: 25731, population: 809313 },
  'Atsimo-Andrefana':    { capital: 'Toliara',         area: 66236, population: 1799088 },
  'Atsimo-Atsinanana':   { capital: 'Farafangana',     area: 18863, population: 1018455 },
  'Atsinanana':          { capital: 'Toamasina',       area: 21934, population: 1484403 },
  'Betsiboka':           { capital: 'Maevatanana',     area: 29890, population: 394561 },
  'Boeny':               { capital: 'Mahajanga',       area: 31046, population: 931171 },
  'Bongolava':           { capital: 'Tsiroanomandidy', area: 16688, population: 522728 },
  'Diana':               { capital: 'Antsiranana',     area: 13318, population: 906480 },
  'Ihorombe':            { capital: 'Ihosy',           area: 26374, population: 419215 },
  'Itasy':               { capital: 'Miarinarivo',     area: 6658,  population: 897962 },
  'Matsiatra Ambony':    { capital: 'Fianarantsoa',    area: 21063, population: 1447296 },
  'Melaky':              { capital: 'Maintirano',      area: 38852, population: 309856 },
  'Menabe':              { capital: 'Morondava',       area: 46121, population: 700577 },
  'Sava':                { capital: 'Sambava',         area: 25518, population: 1123854 },
  'Sofia':               { capital: 'Antsohihy',       area: 50100, population: 1500227 },
  'Vakinankaratra':      { capital: 'Antsirabe',       area: 16688, population: 2074358 },
  'Vatovavy-Fitovinany': { capital: 'Manakara',        area: 19165, population: 1442000 },
};

// Images Unsplash représentatives pour chaque région
export const REGION_IMAGES = {
  'Analamanga':          'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=600&q=80',
  'Diana':               'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=600&q=80',
  'Atsinanana':          'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=600&q=80',
  'Boeny':               'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=600&q=80',
  'Atsimo-Andrefana':    'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600&q=80',
  'Menabe':              'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600&q=80',
  'Sava':                'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80',
  'Sofia':               'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=600&q=80',
  'Alaotra-Mangoro':     'https://images.unsplash.com/photo-1472396961693-142e6e269027?w=600&q=80',
  'Vakinankaratra':      'https://images.unsplash.com/photo-1519659528534-7fd733a832a0?w=600&q=80',
  'Matsiatra Ambony':    'https://images.unsplash.com/photo-1519659528534-7fd733a832a0?w=600&q=80',
  'Analanjirofo':        'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=600&q=80',
  'Androy':              'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600&q=80',
  'Anosy':               'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=600&q=80',
  'Atsimo-Atsinanana':   'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=600&q=80',
  'Betsiboka':           'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=600&q=80',
  'Bongolava':           'https://images.unsplash.com/photo-1519659528534-7fd733a832a0?w=600&q=80',
  'Ihorombe':            'https://images.unsplash.com/photo-1472396961693-142e6e269027?w=600&q=80',
  'Itasy':               'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=600&q=80',
  'Melaky':              'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600&q=80',
  "Amoron'i Mania":      'https://images.unsplash.com/photo-1519659528534-7fd733a832a0?w=600&q=80',
  'Vatovavy-Fitovinany': 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=600&q=80',
};

// Connexions principales entre régions pour l'overlay de lignes
export const REGION_CONNECTIONS = [
  ['Analamanga', 'Vakinankaratra'],
  ['Analamanga', 'Alaotra-Mangoro'],
  ['Analamanga', 'Atsinanana'],
  ['Analamanga', 'Itasy'],
  ['Diana', 'Sava'],
  ['Diana', 'Sofia'],
  ['Sava', 'Analanjirofo'],
  ['Boeny', 'Sofia'],
  ['Boeny', 'Melaky'],
  ['Menabe', 'Atsimo-Andrefana'],
  ['Matsiatra Ambony', 'Vatovavy-Fitovinany'],
  ['Matsiatra Ambony', 'Ihorombe'],
  ['Anosy', 'Androy'],
  ['Alaotra-Mangoro', 'Atsinanana'],
  ["Amoron'i Mania", 'Vakinankaratra'],
  ['Betsiboka', 'Sofia'],
];

// Mapping ADM2 (district) → ADM1 (région) parente
export const ADM2_PARENT = {
  '1er Arrondissement': 'Analamanga',  '2e Arrondissement': 'Analamanga',
  '3e Arrondissement': 'Analamanga',   '4e Arrondissement': 'Analamanga',
  '5e Arrondissement': 'Analamanga',   '6e Arrondissement': 'Analamanga',
  'Antananarivo Atsimondrano': 'Analamanga', 'Antananarivo Avaradrano': 'Analamanga',
  'Ambohidratrimo': 'Analamanga', 'Andramasina': 'Analamanga',
  'Anjozorobe': 'Analamanga', 'Ankazobe': 'Analamanga', 'Manjakandriana': 'Analamanga',
  'Ambatondrazaka': 'Alaotra-Mangoro', 'Amparafaravola': 'Alaotra-Mangoro',
  'Andilamena': 'Alaotra-Mangoro', "Anosibe-An'ala": 'Alaotra-Mangoro',
  'Moramanga': 'Alaotra-Mangoro',
  'Ambositra': "Amoron'i Mania", 'Ambatofinandrahana': "Amoron'i Mania",
  'Fandriana': "Amoron'i Mania", 'Manandriana': "Amoron'i Mania",
  'Fenerive Est': 'Analanjirofo', 'Mananara-Avaratra': 'Analanjirofo',
  'Maroantsetra': 'Analanjirofo', 'Sainte Marie': 'Analanjirofo',
  'Soanierana Ivongo': 'Analanjirofo', 'Vavatenina': 'Analanjirofo',
  'Ambovombe-Androy': 'Androy', 'Bekily': 'Androy', 'Beloha': 'Androy', 'Tsihombe': 'Androy',
  'Amboasary-Atsimo': 'Anosy', 'Betroka': 'Anosy', 'Taolagnaro': 'Anosy',
  'Ankazoabo': 'Atsimo-Andrefana', 'Ampanihy Ouest': 'Atsimo-Andrefana',
  'Benenitra': 'Atsimo-Andrefana', 'Beroroha': 'Atsimo-Andrefana',
  'Betioky Atsimo': 'Atsimo-Andrefana', 'Morombe': 'Atsimo-Andrefana',
  'Sakaraha': 'Atsimo-Andrefana', 'Toliary-I': 'Atsimo-Andrefana', 'Toliary-II': 'Atsimo-Andrefana',
  'Befotaka': 'Atsimo-Atsinanana', 'Farafangana': 'Atsimo-Atsinanana',
  'Midongy-Atsimo': 'Atsimo-Atsinanana', 'Vangaindrano': 'Atsimo-Atsinanana',
  'Vondrozo': 'Atsimo-Atsinanana',
  'Antanambao Manampontsy': 'Atsinanana', 'Brickaville': 'Atsinanana',
  'Mahanoro': 'Atsinanana', 'Marolambo': 'Atsinanana',
  'Toamasina I': 'Atsinanana', 'Toamasina II': 'Atsinanana', 'Vatomandry': 'Atsinanana',
  'Kandreho': 'Betsiboka', 'Maevatanana': 'Betsiboka', 'Tsaratanana': 'Betsiboka',
  'Ambato Boeni': 'Boeny', 'Mahajanga I': 'Boeny', 'Mahajanga II': 'Boeny',
  'Marovoay': 'Boeny', 'Mitsinjo': 'Boeny', 'Soalala': 'Boeny',
  'Fenoarivobe': 'Bongolava', 'Tsiroanomandidy': 'Bongolava',
  'Ambanja': 'Diana', 'Ambilobe': 'Diana', 'Antsiranana I': 'Diana',
  'Antsiranana II': 'Diana', 'Nosy-Be': 'Diana',
  'Iakora': 'Ihorombe', 'Ihosy': 'Ihorombe', 'Ivohibe': 'Ihorombe',
  'Arivonimamo': 'Itasy', 'Miarinarivo': 'Itasy', 'Soavinandriana': 'Itasy',
  'Ambalavao': 'Matsiatra Ambony', 'Ambohimahasoa': 'Matsiatra Ambony',
  'Fianarantsoa I': 'Matsiatra Ambony', 'Ikalamavony': 'Matsiatra Ambony',
  'Isandra': 'Matsiatra Ambony', 'Lalangina': 'Matsiatra Ambony',
  'Vohibato': 'Matsiatra Ambony',
  'Ambatomainty': 'Melaky', 'Antsalova': 'Melaky', 'Besalampy': 'Melaky',
  'Maintirano': 'Melaky', 'Morafenobe': 'Melaky',
  'Belo Sur Tsiribihina': 'Menabe', 'Mahabo': 'Menabe', 'Manja': 'Menabe',
  'Miandrivazo': 'Menabe', 'Morondava': 'Menabe',
  'Andapa': 'Sava', 'Antalaha': 'Sava', 'Sambava': 'Sava', 'Vohemar': 'Sava',
  'Analalava': 'Sofia', 'Antsohihy': 'Sofia', 'Bealanana': 'Sofia',
  'Befandriana Nord': 'Sofia', 'Mampikony': 'Sofia', 'Mandritsara': 'Sofia',
  'Port-Berge (Boriziny-Vaovao)': 'Sofia',
  'Ambatolampy': 'Vakinankaratra', 'Antanifotsy': 'Vakinankaratra',
  'Antsirabe I': 'Vakinankaratra', 'Antsirabe II': 'Vakinankaratra',
  'Betafo': 'Vakinankaratra', 'Faratsiho': 'Vakinankaratra',
  'Mandoto': 'Vakinankaratra',
  'Ifanadiana': 'Vatovavy-Fitovinany', 'Ikongo': 'Vatovavy-Fitovinany',
  'Manakara Atsimo': 'Vatovavy-Fitovinany', 'Mananjary': 'Vatovavy-Fitovinany',
  'Nosy-Varika': 'Vatovavy-Fitovinany', 'Vohipeno': 'Vatovavy-Fitovinany',
};

// Données mock agricoles (à remplacer par appel API plus tard)
export const REGION_STATS = Object.fromEntries(
  Object.keys(REGION_INFO).map(name => [name, {
    rendement_riz: Math.round(50 + Math.random() * 40),
    surface_cultivee: Math.round(10000 + Math.random() * 50000),
    production: Math.round(20000 + Math.random() * 100000),
    score_securite: Math.round(40 + Math.random() * 50),
  }])
);
